### ISSUE TITLE
What's the alternative operation to `conan profile detect` ? It is may be deleted in the coming future.

### ISSUE THREAD

**Issue by uniqss** [Moxibyte/MoxPP#3]
Thanks for your repo and the videos on youtube!
As the warning mentioned in [https://docs.conan.io/2.0/reference/commands/profile.html](https://docs.conan.io/2.0/reference/commands/profile.html)
![image](https://github.com/Moxibyte/MoxPP/assets/48117715/2ffc6d7e-e200-404e-9183-2314c09fa809)
`conan profile detect` may be deleted or not supported in the coming future. I am just looking for a modern easy to use c++ package management tools today, and found your video on youtube, It is very helpful, but I run into some problem. `conan profile detect` is not working in the latest relase package on windows.  Perhaps it is because I downloaded the prebuilt version, not install python3 and pip install conan. I will have a try later, but the command `conan profile detect` may need some alternative. I searched, but not found it. I'm a newbie to conan. Any help appreciated!

**Comment by Ohjurot** [comment]
The profile is a set of default settings that conan uses when it downloads dependencies. They include things like `compiler`, `compiler_version`, `os`, `cppversion`, ... 

Currently, (with pip install) it works for me on Windows (just did it a few days ago on my new work computer). I would recommend using it as long as it works, because it's just very simple to get started. As long as it works (for me, it does) I will continue using it.

The problem with `detect` is that it is never going to be deterministic what results you get. If you have multiple version of Visual Studio and maybe also gcc and clang. Then conan can't detect what your preferred system is and thus may produce a non-fitting profile. 

The alternative is to create the profile manually. When they really remove detect, then I will need to write and record another tutorial that shows how to configure a profile correctly. 

This is what currently works for me:
```ini
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[build_requires]
[env]
```
from `%UserProfile%/.conan/profiles/default`

**Comment by uniqss** [comment]
I tried last night by installing python3 and do `pip install conan` on windows and it works. Thanks very much for your help! Yes, it's very easy to use. I will check it on linux today.
On windows I prefer this config ( static runtime have larger size, but don't need to install the vc runtime package ):
```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=static
compiler.version=193
os=Windows

```
